# Generated by Django 6.0.3 on 2026-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdraw_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failing', 'Failing')], default='pending', max_length=10),
        ),
    ]
