# Generated by Django 6.0.3 on 2026-04-03 15:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plantype', models.CharField(choices=[('REGULAR', 'Regular'), ('GOLD', 'Gold'), ('DIAMOND', 'Diamond'), ('PLATINIUM', 'Platinium')], default='REGULAR', max_length=30)),
                ('percent_increment', models.DecimalField(decimal_places=4, help_text='Daily percent (e.g., 0.5000 for 0.5%)', max_digits=6)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('short_description', models.CharField(blank=True, help_text='A brief summary of the product (max 255 characters).', max_length=255, null=True)),
                ('long_description', models.TextField(blank=True, help_text='A detailed description of the product.', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('is_mirrowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.portfolio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.plan')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('after_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plan.orderplan')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField()),
                ('delta_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percent_applied', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cumulative_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plan.orderplan')),
            ],
            options={
                'indexes': [models.Index(fields=['order_plan', 'snapshot_at'], name='plan_orderp_order_p_1880ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['status', 'start_at'], name='plan_orderp_status_aeb3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['order_plan', 'created_at'], name='plan_transa_order_p_1ee4c3_idx'),
        ),
    ]
