# Generated by Django 6.0.3 on 2026-04-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_plan_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlanMonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('days', models.IntegerField()),
                ('percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cumulative_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedule', to='plan.orderplan')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('order_plan', 'year', 'month')},
            },
        ),
    ]
