# Generated by Django 6.0.3 on 2026-04-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_orderplanmonthlyschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlanMonthlySchedule',
        ),
    ]
