# Generated by Django 6.0.3 on 2026-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_delete_orderplanmonthlyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplan',
            name='monthly_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
