# Generated by Django 6.0.3 on 2026-04-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_orderplan_monthly_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderplan',
            options={'ordering': ['-created_at']},
        ),
    ]
